### ISSUE TITLE
search results should stand out more

### ISSUE THREAD

**Issue by techieshark** [river-jade/donations-visualiser#13]
Currently if a user searches via the search bar in the filter panel, results are hard to see (at least for me). At first, I actually thought the search function didn't work. We might switch to blue? (See bottom of this issue for what that looks like.)

![image](https://cloud.githubusercontent.com/assets/1072292/15271300/b28764ca-1a85-11e6-9ff7-1e6a8de349fe.png)

Result looks like:

![colortest](https://cloud.githubusercontent.com/assets/1072292/15271301/bb48c5ae-1a85-11e6-8e85-7b98860891e8.jpg)

Search matches are shown as pink (rgb#ff1d8e) with a thin dark border. Non results are grey (rgb#808080).

The best test I can think of to demonstrate the lack of contrast would be to look at the [WCAG 2.0](http://www.w3.org/TR/WCAG20/) guidelines. 

Here's what I found: 

http://leaverou.github.io/contrast-ratio/#%23808080-on-%23ff1d8e

![image](https://cloud.githubusercontent.com/assets/1072292/15271321/69d13fa2-1a86-11e6-97ee-a56ac6477757.png)

http://webaim.org/resources/contrastchecker/

![image](https://cloud.githubusercontent.com/assets/1072292/15271319/5ef57bf2-1a86-11e6-9884-4f53a78cca2f.png)

A blue color seems to work better (for me, though the contrast test above shows it as only slightly better):

![image](https://cloud.githubusercontent.com/assets/1072292/15271346/37f201d2-1a87-11e6-96cd-8e2593ebb667.png)

If not that, then http://colorbrewer2.org/ might be a good resource to check for color sets.

**Comment by river-jade** [comment]
Thanks for the feedback. Done. I went for #00FFFF.

**Comment by techieshark** [comment]
Ah nice, so much better! Thanks!
